const ridesData = [
  {
    city: "Delhi",
    address: "Connaught Place, New Delhi",
    destination: "Vaishali Nagar, Jaipur",
    price: "₹650",
    time: "06:00 - 09:00",
    name: "John Doe",
    amenities: ["Max. 2 in the back", "Instant booking", "Pets allowed"],
  },
  {
    city: "Delhi",
    address: "Karol Bagh, New Delhi",
    destination: "Bani Park, Jaipur",
    price: "₹700",
    time: "06:30 - 09:30",
    name: "Jane Smith",
    amenities: ["Instant booking"],
  },
  {
    city: "Delhi",
    address: "Saket, New Delhi",
    destination: "Malviya Nagar, Jaipur",
    price: "₹750",
    time: "07:00 - 10:00",
    name: "Ravi Kumar",
    amenities: ["Max. 2 in the back", "Smoking allowed"],
  },
  {
    city: "Delhi",
    address: "Lajpat Nagar, New Delhi",
    destination: "Ajmer Road, Jaipur",
    price: "₹800",
    time: "07:30 - 10:30",
    name: "Amit Sharma",
    amenities: ["Instant booking", "Smoking allowed", "Pets allowed"],
  },
  {
    city: "Delhi",
    address: "Vasant Kunj, New Delhi",
    destination: "Civil Lines, Jaipur",
    price: "₹720",
    time: "08:00 - 11:00",
    name: "Sunil Gupta",
    amenities: ["Max. 2 in the back", "Pets allowed"],
  },
  {
    city: "Delhi",
    address: "Rohini, New Delhi",
    destination: "Vaishali Nagar, Jaipur",
    price: "₹650",
    time: "08:30 - 11:30",
    name: "Neha Kapoor",
    amenities: ["Instant booking", "Pets allowed"],
  },
  {
    city: "Delhi",
    address: "Nehru Place, New Delhi",
    destination: "Mansarovar, Jaipur",
    price: "₹780",
    time: "09:00 - 12:00",
    name: "Vikram Singh",
    amenities: ["Max. 2 in the back", "Smoking allowed"],
  },
  {
    city: "Delhi",
    address: "Paharganj, New Delhi",
    destination: "Bapu Nagar, Jaipur",
    price: "₹650",
    time: "09:30 - 12:30",
    name: "Priya Yadav",
    amenities: ["Instant booking", "Pets allowed"],
  },
  {
    city: "Delhi",
    address: "Dwarka, New Delhi",
    destination: "Malviya Nagar, Jaipur",
    price: "₹700",
    time: "10:00 - 13:00",
    name: "Mohit Verma",
    amenities: ["Smoking allowed", "Pets allowed"],
  },
  {
    city: "Delhi",
    address: "New Friends Colony, New Delhi",
    destination: "Vaishali Nagar, Jaipur",
    price: "₹730",
    time: "10:30 - 13:30",
    name: "Sushil Choudhury",
    amenities: ["Max. 2 in the back", "Instant booking"],
  },
  {
    city: "Delhi",
    address: "Faridabad, New Delhi",
    destination: "Bani Park, Jaipur",
    price: "₹710",
    time: "11:00 - 14:00",
    name: "Kiran Bedi",
    amenities: ["Pets allowed"],
  },
  {
    city: "Delhi",
    address: "Janakpuri, New Delhi",
    destination: "Ajmer Road, Jaipur",
    price: "₹690",
    time: "11:30 - 14:30",
    name: "Asha Rani",
    amenities: ["Instant booking", "Pets allowed"],
  },
  {
    city: "Delhi",
    address: "Kailash Colony, New Delhi",
    destination: "Civil Lines, Jaipur",
    price: "₹750",
    time: "12:00 - 15:00",
    name: "Anil Kumar",
    amenities: ["Max. 2 in the back"],
  },
  {
    city: "Delhi",
    address: "Hauz Khas, New Delhi",
    destination: "Mansarovar, Jaipur",
    price: "₹710",
    time: "12:30 - 15:30",
    name: "Arvind Bhatt",
    amenities: ["Instant booking", "Smoking allowed"],
  },
  {
    city: "Delhi",
    address: "Okhla, New Delhi",
    destination: "Bapu Nagar, Jaipur",
    price: "₹680",
    time: "13:00 - 16:00",
    name: "Geeta Rani",
    amenities: ["Max. 2 in the back", "Pets allowed"],
  },
  {
    city: "Delhi",
    address: "Chandni Chowk, New Delhi",
    destination: "Vaishali Nagar, Jaipur",
    price: "₹640",
    time: "13:30 - 16:30",
    name: "Anil Patel",
    amenities: ["Instant booking", "Smoking allowed"],
  },
  {
    city: "Delhi",
    address: "Sarai Kale Khan, New Delhi",
    destination: "Malviya Nagar, Jaipur",
    price: "₹700",
    time: "14:00 - 17:00",
    name: "Amit Patel",
    amenities: ["Pets allowed"],
  },
  {
    city: "Delhi",
    address: "Ashok Vihar, New Delhi",
    destination: "Ajmer Road, Jaipur",
    price: "₹760",
    time: "14:30 - 17:30",
    name: "Vandana Mehta",
    amenities: ["Max. 2 in the back", "Instant booking"],
  },
  {
    city: "Delhi",
    address: "Shahdara, New Delhi",
    destination: "Mansarovar, Jaipur",
    price: "₹670",
    time: "15:00 - 18:00",
    name: "Dinesh Kumar",
    amenities: ["Smoking allowed"],
  },
  {
    city: "Delhi",
    address: "Vikaspuri, New Delhi",
    destination: "Bani Park, Jaipur",
    price: "₹690",
    time: "15:30 - 18:30",
    name: "Tanu Verma",
    amenities: ["Instant booking", "Pets allowed"],
  },
  {
    city: "Delhi",
    address: "Sultanpur, New Delhi",
    destination: "Bapu Nagar, Jaipur",
    price: "₹700",
    time: "16:00 - 19:00",
    name: "Pooja Thakur",
    amenities: ["Max. 2 in the back", "Instant booking"],
  }
];

export default ridesData;
